openapi: 3.0.1
info:
  contact:
    email: info@gemini-commerce.com
    name: Gemini Team
  description: API for managing wishlists
  license:
    name: Gemini fair use license
    url: https://gemini-commerce.com/api/fair-use-license
  title: Wishlist Service
  version: v1
servers:
- url: https://wishlist.api.gogemini.io/
security:
- Authorization: []
tags:
- name: Wishlist
paths:
  /wishlist.Wishlist/AddItemToWishlist:
    post:
      operationId: Wishlist_AddItemToWishlist
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistAddItemToWishlistRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistWishlistItemResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/AreItemsInWishlists:
    post:
      operationId: Wishlist_AreItemsInWishlists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistAreItemsInWishlistsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistAreItemsInWishlistsResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/BulkCreateSharing:
    post:
      operationId: Wishlist_BulkCreateSharing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistBulkCreateSharingRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistBulkCreateSharingResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Sharing endpoints
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/BulkRemoveItemsFromWishlists:
    post:
      operationId: Wishlist_BulkRemoveItemsFromWishlists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistBulkRemoveItemsFromWishlistsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistBulkRemoveItemsFromWishlistsResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: BulkRemoveItemsFromWishlists removes items from wishlists.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/BulkRevokeSharing:
    post:
      operationId: Wishlist_BulkRevokeSharing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistBulkRevokeSharingRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistBulkRevokeSharingResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/CreateWishlist:
    post:
      operationId: Wishlist_CreateWishlist
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistCreateWishlistRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistWishlistResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/DeleteWishlist:
    post:
      operationId: Wishlist_DeleteWishlist
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistDeleteWishlistRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistDeleteWishlistResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/GetItemFromWishlist:
    post:
      operationId: Wishlist_GetItemFromWishlist
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistGetItemFromWishlistRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistWishlistItemResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/GetWishlistById:
    post:
      operationId: Wishlist_GetWishlistById
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistGetWishlistByIdRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistWishlistResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/GetWishlistBySharedCode:
    post:
      operationId: Wishlist_GetWishlistBySharedCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistGetWishlistBySharedCodeRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistWishlistResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/ListWishlistItems:
    post:
      operationId: Wishlist_ListWishlistItems
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistListWishlistItemsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistListWishlistItemsResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/ListWishlists:
    post:
      operationId: Wishlist_ListWishlists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistListWishlistsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistListWishlistsResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/MergeWishlists:
    post:
      operationId: Wishlist_MergeWishlists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistMergeWishlistsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistWishlistResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/RemoveItemFromWishlist:
    post:
      operationId: Wishlist_RemoveItemFromWishlist
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistRemoveItemFromWishlistRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistRemoveItemFromWishlistResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/UpdateItemInWishlist:
    post:
      operationId: Wishlist_UpdateItemInWishlist
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistUpdateItemInWishlistRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistWishlistItemResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
  /wishlist.Wishlist/UpdateWishlist:
    post:
      operationId: Wishlist_UpdateWishlist
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlistUpdateWishlistRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wishlistWishlistResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - Wishlist
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    ListWishlistsRequestFilter:
      properties:
        customerGrn:
          description: "If the customer GRN is set on JWT, it will be used as default.\
            \ Otherwise, it will be used the customer_grn field."
          type: string
      type: object
    protobufAny:
      additionalProperties:
        type: object
      properties:
        '@type':
          type: string
      type: object
    rpcStatus:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        details:
          items:
            $ref: '#/components/schemas/protobufAny'
          type: array
      type: object
    wishlistAddItemToWishlistRequest:
      properties:
        tenantId:
          type: string
        wishlistId:
          type: string
        itemGrn:
          type: string
        preferredQuantity:
          format: uint64
          type: string
        description:
          $ref: '#/components/schemas/wishlistLocalizedText'
        customerGrn:
          title: The customer adds the item to the wishlist
          type: string
      required:
      - itemGrn
      - tenantId
      - wishlistId
      type: object
    wishlistAreItemsInWishlistsRequest:
      properties:
        tenantId:
          type: string
        wishlistId:
          type: string
        customerGrn:
          type: string
        itemGrns:
          items:
            type: string
          title: Max 500 items per request
          type: array
      required:
      - itemGrns
      - tenantId
      type: object
    wishlistAreItemsInWishlistsResponse:
      example:
        itemGrnMap:
          key:
            wishlistGrnToWishlistItemGrnMap:
              key: wishlistGrnToWishlistItemGrnMap
      properties:
        itemGrnMap:
          additionalProperties:
            $ref: '#/components/schemas/wishlistAreItemsInWishlistsResponsePayload'
          type: object
      type: object
    wishlistAreItemsInWishlistsResponsePayload:
      example:
        wishlistGrnToWishlistItemGrnMap:
          key: wishlistGrnToWishlistItemGrnMap
      properties:
        wishlistGrnToWishlistItemGrnMap:
          additionalProperties:
            type: string
          type: object
      type: object
    wishlistBulkCreateSharingRequest:
      properties:
        tenantId:
          type: string
        sharingRequests:
          items:
            $ref: '#/components/schemas/wishlistSharingRequest'
          type: array
      type: object
    wishlistBulkCreateSharingResponse:
      example:
        sharingResponses:
        - createdAt: 2000-01-23T04:56:07.000+00:00
          customerGrn: customerGrn
          sharingGrn: sharingGrn
          permission: null
          customerAggregationId: customerAggregationId
          wishlistId: wishlistId
          sharingId: sharingId
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - createdAt: 2000-01-23T04:56:07.000+00:00
          customerGrn: customerGrn
          sharingGrn: sharingGrn
          permission: null
          customerAggregationId: customerAggregationId
          wishlistId: wishlistId
          sharingId: sharingId
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        sharingResponses:
          items:
            $ref: '#/components/schemas/wishlistSharingResponse'
          type: array
      type: object
    wishlistBulkRemoveItemsFromWishlistsRequest:
      properties:
        tenantId:
          type: string
        itemGrns:
          description: Item GRNs to remove from wishlists. Max 500 items per request.
          items:
            type: string
          type: array
        wishlistIds:
          description: |-
            Wishlist IDs to remove items from. Max 500 wishlists per request.
            If not provided, items will be removed from all wishlists.
          items:
            type: string
          type: array
      required:
      - itemGrns
      - tenantId
      type: object
    wishlistBulkRemoveItemsFromWishlistsResponse:
      type: object
    wishlistBulkRevokeSharingRequest:
      properties:
        tenantId:
          type: string
        sharingIds:
          items:
            type: string
          type: array
      type: object
    wishlistBulkRevokeSharingResponse:
      type: object
    wishlistCreateWishlistRequest:
      properties:
        tenantId:
          type: string
        privacy:
          $ref: '#/components/schemas/wishlistPrivacy'
        label:
          $ref: '#/components/schemas/wishlistLocalizedText'
        description:
          $ref: '#/components/schemas/wishlistLocalizedText'
        customerGrn:
          description: "If the customer GRN is set on JWT, it will be used as default.\
            \ Otherwise, it will be used the customer_grn field."
          type: string
        isDefault:
          title: "If is the first wishlist for the customer, it will be set as default"
          type: boolean
      required:
      - privacy
      - tenantId
      type: object
    wishlistDeleteWishlistRequest:
      properties:
        tenantId:
          type: string
        id:
          type: string
      required:
      - id
      - tenantId
      type: object
    wishlistDeleteWishlistResponse:
      type: object
    wishlistGetItemFromWishlistRequest:
      properties:
        tenantId:
          type: string
        id:
          type: string
      required:
      - id
      - tenantId
      type: object
    wishlistGetWishlistByIdRequest:
      properties:
        tenantId:
          type: string
        id:
          type: string
      required:
      - id
      - tenantId
      type: object
    wishlistGetWishlistBySharedCodeRequest:
      properties:
        tenantId:
          type: string
        sharedCode:
          type: string
        customerGrn:
          description: "If the customer GRN is set on JWT, it will be used as default.\
            \ Otherwise, it will be used the customer_grn field."
          type: string
      required:
      - sharedCode
      - tenantId
      type: object
    wishlistListWishlistItemsRequest:
      properties:
        tenantId:
          type: string
        wishlistId:
          type: string
        customerGrn:
          title: "If customer_grn is not provided, the wishlist will be returned only\
            \ if it is not PRIVATE"
          type: string
        pageSize:
          format: int64
          type: integer
        pageToken:
          type: string
      required:
      - tenantId
      - wishlistId
      type: object
    wishlistListWishlistItemsResponse:
      example:
        wishlistItems:
        - grn: grn
          itemGrn: itemGrn
          addedAt: 2000-01-23T04:56:07.000+00:00
          addedByCustomerGrn: addedByCustomerGrn
          description:
            value:
              key: value
          id: id
          wishlistId: wishlistId
          preferredQuantity: preferredQuantity
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - grn: grn
          itemGrn: itemGrn
          addedAt: 2000-01-23T04:56:07.000+00:00
          addedByCustomerGrn: addedByCustomerGrn
          description:
            value:
              key: value
          id: id
          wishlistId: wishlistId
          preferredQuantity: preferredQuantity
          updatedAt: 2000-01-23T04:56:07.000+00:00
        nextPageToken: nextPageToken
      properties:
        wishlistItems:
          items:
            $ref: '#/components/schemas/wishlistWishlistItemResponse'
          type: array
        nextPageToken:
          type: string
      type: object
    wishlistListWishlistsRequest:
      properties:
        tenantId:
          type: string
        pageSize:
          format: int64
          type: integer
        pageToken:
          type: string
        filter:
          $ref: '#/components/schemas/ListWishlistsRequestFilter'
        filterMask:
          type: string
      required:
      - tenantId
      type: object
    wishlistListWishlistsResponse:
      example:
        wishlist:
        - createdAt: 2000-01-23T04:56:07.000+00:00
          grn: grn
          isDefault: true
          customerGrn: customerGrn
          privacy: null
          description:
            value:
              key: value
          id: id
          label:
            value:
              key: value
          sharedCode: sharedCode
          itemsCount: itemsCount
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - createdAt: 2000-01-23T04:56:07.000+00:00
          grn: grn
          isDefault: true
          customerGrn: customerGrn
          privacy: null
          description:
            value:
              key: value
          id: id
          label:
            value:
              key: value
          sharedCode: sharedCode
          itemsCount: itemsCount
          updatedAt: 2000-01-23T04:56:07.000+00:00
        nextPageToken: nextPageToken
      properties:
        wishlist:
          items:
            $ref: '#/components/schemas/wishlistWishlistResponse'
          type: array
        nextPageToken:
          type: string
      type: object
    wishlistLocalizedText:
      example:
        value:
          key: value
      properties:
        value:
          additionalProperties:
            type: string
          type: object
      type: object
    wishlistMergeWishlistsRequest:
      properties:
        tenantId:
          type: string
        startingWishlistId:
          type: string
        customerGrn:
          description: "If the customer GRN is set on JWT, it will be used as default.\
            \ Otherwise, it will be used the customer_grn field."
          type: string
        targetWishlistId:
          description: The wishlist to merge into the starting wishlist.
          type: string
      required:
      - customerGrn
      - startingWishlistId
      - tenantId
      type: object
    wishlistPermission:
      default: UNKNOWN_PERMISSION
      enum:
      - UNKNOWN_PERMISSION
      - VIEW_PERMISSION
      - EDIT_PERMISSION
      type: string
    wishlistPrivacy:
      default: PRIVACY_UNKNOWN
      enum:
      - PRIVACY_UNKNOWN
      - PRIVACY_PUBLIC
      - PRIVACY_PRIVATE
      - PRIVACY_SHARED
      type: string
    wishlistRemoveItemFromWishlistRequest:
      properties:
        tenantId:
          type: string
        id:
          type: string
      required:
      - id
      - tenantId
      type: object
    wishlistRemoveItemFromWishlistResponse:
      type: object
    wishlistSharingRequest:
      properties:
        wishlistId:
          type: string
        permission:
          $ref: '#/components/schemas/wishlistPermission'
        customerGrn:
          type: string
        customerAggregationId:
          type: string
      type: object
    wishlistSharingResponse:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        customerGrn: customerGrn
        sharingGrn: sharingGrn
        permission: null
        customerAggregationId: customerAggregationId
        wishlistId: wishlistId
        sharingId: sharingId
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        sharingId:
          type: string
        sharingGrn:
          type: string
        wishlistId:
          type: string
        permission:
          $ref: '#/components/schemas/wishlistPermission'
        customerGrn:
          type: string
        customerAggregationId:
          type: string
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      type: object
    wishlistUpdateItemInWishlistRequest:
      properties:
        tenantId:
          type: string
        id:
          type: string
        payload:
          $ref: '#/components/schemas/wishlistUpdateItemInWishlistRequestPayload'
        payloadMask:
          type: string
      required:
      - id
      - payload
      - payloadMask
      - tenantId
      type: object
    wishlistUpdateItemInWishlistRequestPayload:
      properties:
        preferredQuantity:
          format: uint64
          type: string
        description:
          $ref: '#/components/schemas/wishlistLocalizedText'
        customerGrn:
          title: The customer adds the item to the wishlist
          type: string
      type: object
    wishlistUpdateWishlistRequest:
      properties:
        tenantId:
          type: string
        id:
          type: string
        payload:
          $ref: '#/components/schemas/wishlistUpdateWishlistRequestPayload'
        payloadMask:
          type: string
      required:
      - id
      - payload
      - payloadMask
      - tenantId
      type: object
    wishlistUpdateWishlistRequestPayload:
      properties:
        privacy:
          $ref: '#/components/schemas/wishlistPrivacy'
        label:
          $ref: '#/components/schemas/wishlistLocalizedText'
        description:
          $ref: '#/components/schemas/wishlistLocalizedText'
        isDefault:
          type: boolean
      type: object
    wishlistWishlistItemResponse:
      example:
        grn: grn
        itemGrn: itemGrn
        addedAt: 2000-01-23T04:56:07.000+00:00
        addedByCustomerGrn: addedByCustomerGrn
        description:
          value:
            key: value
        id: id
        wishlistId: wishlistId
        preferredQuantity: preferredQuantity
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          type: string
        grn:
          type: string
        wishlistId:
          type: string
        itemGrn:
          type: string
        preferredQuantity:
          format: uint64
          type: string
        description:
          $ref: '#/components/schemas/wishlistLocalizedText'
        addedByCustomerGrn:
          type: string
        addedAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      type: object
    wishlistWishlistResponse:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        grn: grn
        isDefault: true
        customerGrn: customerGrn
        privacy: null
        description:
          value:
            key: value
        id: id
        label:
          value:
            key: value
        sharedCode: sharedCode
        itemsCount: itemsCount
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          type: string
        grn:
          type: string
        sharedCode:
          type: string
        privacy:
          $ref: '#/components/schemas/wishlistPrivacy'
        label:
          $ref: '#/components/schemas/wishlistLocalizedText'
        description:
          $ref: '#/components/schemas/wishlistLocalizedText'
        customerGrn:
          type: string
        isDefault:
          type: boolean
        itemsCount:
          format: uint64
          type: string
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      type: object
  securitySchemes:
    Authorization:
      in: header
      name: Authorization
      type: apiKey
    standardAuthorization:
      flows:
        implicit:
          scopes: {}
      type: oauth2
x-original-swagger-version: "2.0"

